### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by allojohn** [csev/uninstall-python3#1]
man, it fails.

**Comment by Noverish** [comment]
People who installed python via homebrew do not work this script
Because, all the files related to python are in ' /usr/local/Cellar/python/3.x.x', not in '/Library/Frameworks/Python.framework/Versions/3.x.x' 

So, just uninstalling it is worked for me

``` shell
$ brew uninstall python
```

You can also check whether python was installed by homebrew

``` shell
$ ls -l /usr/local/bin | grep 'python'
```

**Comment by allojohn** [comment]
thanks!
